[env] ## tells cargo make that we're in the context of a Cargo workspace
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config] ## we want most/all of our tasks to run in the context of a workspace
default_to_workspace = false

[tasks.docker-build]
command = "docker-compose"
args = [
    "-f", "./deploy/docker-compose.postgres.yaml",
    "up",
    "--build"
]

[tasks.docker-start]
command = "docker-compose"
args = [
    "-f", "./deploy/docker-compose.postgres.yaml",
    "start"
]
