[env] ## tells cargo make that we're in the context of a Cargo workspace
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config] ## we want most/all of our tasks to run in the context of a workspace
default_to_workspace = false

## To start the API outside the Docker context
[tasks.dev]
command = "cargo"
args = ["run"]
dependencies = ["postgres"]

## Build all Docker containers.
[tasks.docker]
command = "docker-compose"
args = [
    "-f", "./deploy/docker-compose.postgres.yaml",
    "up",
    "--build"
]

## Start all Docker containers.
[tasks.docker-start]
command = "docker-compose"
args = [
    "-f", "./deploy/docker-compose.postgres.yaml",
    "start"
]

## Start only Postgres Docker container.
[tasks.postgres]
command = "docker-compose"
args = [
    "-f", "./deploy/docker-compose.postgres.yml",
    "start"
]


[tasks.migrate] ## ensure Postgres is running, the container has a bit of warmup time causing migrations to fail
install_crate = "sqlx"
command = "sqlx"
args = ["migrate", "run"]
dependencies = ["postgres"]
