api:
  port: 8080
  host: 0.0.0.0
  frontend_origin: http://localhost:3000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "realworld"
  max_connections: 100
  require_ssl: false
jwt_token:
  secret_key: 465465456321454
